name: CI

on:
  push:
    branches: [ main, feat/** ]
  pull_request:
    branches: [ main ]

jobs:
  analyze-and-test:
    name: Analyze and unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache pub packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Cache npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze
        run: flutter analyze

      - name: Run unit tests
        run: flutter test --no-pub -r expanded

  integration-emulator:
    name: Integration tests (Firestore emulator)
    runs-on: ubuntu-latest
    needs: analyze-and-test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java (required by Firestore emulator)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Node (for firebase-tools)
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools@latest

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Run integration test with emulator
        # Use firebase emulators:exec to start emulator and run the test command
        env:
          # Ensure emulator REST client uses this host:port
          FIRESTORE_EMULATOR_HOST: 127.0.0.1:8080
        run: |
          npx firebase --version
          firebase emulators:exec --only firestore "bash -lc 'export FIRESTORE_EMULATOR_HOST=127.0.0.1:8080; flutter test test/integration/sync_emulator_test.dart -r expanded'"
